// <auto-generated />
namespace SportsDB.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-alpha1-21218")]
    public sealed partial class Structuresetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Structuresetup));
        
        string IMigrationMetadata.Id
        {
            get { return "201404101628090_Structuresetup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
